// Code generated by pkg/codegen/config/main.go. DO NOT EDIT.
// Package buildconfig contains a set of exported constants that represent configuration variables of Rancher at build-time.
package buildconfig

const (
	DevChartsBranch                 = "2.15-rpm"
	DevChartsSource                 = "https://github.com/diogoasouza/ob-team-charts"
	K3sTestingMaxVersion            = "v1.36.0-k3s1"
	K3sTestingMinVersion            = "v1.34.7+k3s1"
	KuberlrVersion                  = "v8"
	RancherMonitoringVersion        = "109.0.2+up80.9.1-rancher.8"
	RancherProjectMonitoringVersion = "1.0.0"
)
