#!/usr/bin/env bash
set -e

source $(dirname $0)/version
DOCKER_TARGET=${DOCKER_TARGET:-"-${BUILD_TARGET}"}

cd $(dirname $0)/..

echo "Starting \`${BUILD_TARGET}\` image packaging:";

DOCKERFILE=package/Dockerfile${DOCKER_TARGET}
echo "Building \`${IMAGE}\` from \`${DOCKERFILE}\`:";

if [[ ${USE_DOCKER_BUILDX} -eq 1 ]]; then
  docker buildx build --platform linux/amd64,linux/arm64 -f "${DOCKERFILE}" --build-arg RANCHER_PROJECT_MONITORING=$RANCHER_PROJECT_MONITORING --build-arg YQ_CHECKSUM_AMD64=$YQ_CHECKSUM_AMD64 --build-arg YQ_CHECKSUM_ARM64=$YQ_CHECKSUM_ARM64 -t "${IMAGE}" .
else
  docker build -f "${DOCKERFILE}" --build-arg RANCHER_PROJECT_MONITORING=$RANCHER_PROJECT_MONITORING --build-arg YQ_CHECKSUM_AMD64=$YQ_CHECKSUM_AMD64 --build-arg YQ_CHECKSUM_ARM64=$YQ_CHECKSUM_ARM64 -t "${IMAGE}" .
fi

echo "Completed building ${IMAGE} container image"
